config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  resources :articles do
  	resources :comments
  	
  end
  get 'artikel' => 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
		length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]
	def index
		@article = Article.all
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(artricle_params)
		if @article.save
			redirect_to @article
		else
			render "new"
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
	  @article = Article.find(params[:id])
 
	  if @article.update(artricle_params)
	    redirect_to @article
	  else
	    render 'edit'
	  end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to  articles_path
	end

	private
	def artricle_params
		params.require(:article).permit(:title, :text)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", only: :destroy
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<%= link_to 'Back', articles_path,:class => "btn btn-success" %><hr>
<h1>Edit article</h1><hr>
 
<%= form_with(model: @article, local: true) do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title,:class => "sr-only" %><br>
    <%= form.text_field :title, :class => "form form-control" %>
  </p>
 
  <p>
    <%= form.label :text, :class => "sr-only" %><br>
    <%= form.text_area :text, :class => "form form-control" %>
  </p>
 
  <p>
    <%= form.submit :class => "btn btn-primary" %>
  </p>
 
<% end %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 
<table class="table table-responsive">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @article.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>Create Article</h1><hr>
<%= form_with scope: :article, url: articles_path, local: true do |f| %>
<% if @article.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
	<p>
	<%= pluralize(@article.errors.count, "error") %> prohibited
	this article from being saved:
	</p>
	<ul>
		<% @article.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<p>
	<%= f.label :title, :class => "sr-only" %><br>
	<%= f.text_area :title ,:class => "form form-control", placeholder: "Title"%>
</p>
<p>
	<%= f.label :text, :class => "sr-only" %><br>
	<%= f.text_area :text, :class => "form-control", placeholder: "Text" %>
</p>
<p>
	<%= f.submit :class => "btn btn-primary" %>
</p>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %><br>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter, :class => "sr-only" %><br>
    <%= form.text_field :commenter, :class => "form form-control", placeholder: "Commenter"  %>
  </p>
  <p>
    <%= form.label :body, :class => "sr-only" %><br>
    <%= form.text_area :body, :class => "form form-control", placeholder: "Body" %>
  </p>
  <p>
    <%= form.submit :class => "btn btn-primary" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Playground</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "Home", root_path,class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Article", articles_path,class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Create Article", new_article_path,class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>